"""
Configuration surface for the RoM (Recomputation-or-Migration) scheduler.

All fields can be overridden at runtime via environment variables:

  ROM_POLICY                  rom | always_migrate | always_recompute
  ROM_SIM_BANDWIDTH_MBPS      float   (default: 10_000)
  ROM_MONITOR_INTERVAL_S      float   (default: 1.0)
  ROM_MONITOR_ENABLED         0 | 1   (default: 1)
  ROM_LOG_FILE                path    (default: /tmp/rom_decisions.jsonl)
  ROM_NUM_LAYERS              int     (model architecture override)
  ROM_NUM_KV_HEADS            int     (model architecture override)
  ROM_HEAD_DIM                int     (model architecture override)
  ROM_DTYPE_BYTES             int     (default: 2 for fp16/bf16)

Usage
-----
    from distserve.rom_config import ROMConfig

    # Pure defaults
    cfg = ROMConfig()

    # Override from environment (called at engine startup)
    cfg = ROMConfig.from_env()

    # Programmatic construction (tests, benchmarks)
    cfg = ROMConfig(policy="always_recompute", sim_bandwidth_mbps=1000.0)
    cfg.validate()
"""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Dict

# ── Supported decision policies ─────────────────────────────────────────────
#
#   "rom"               Choose the faster path based on cost estimates.
#   "always_migrate"    Always transfer the existing KV cache (baseline).
#   "always_recompute"  Always re-run prefill (baseline).
#
VALID_POLICIES = frozenset({"rom", "always_migrate", "always_recompute"})


@dataclass
class ROMConfig:
    """
    Configuration for the RoM scheduler.

    Attributes
    ----------
    policy : str
        Decision policy.  One of "rom", "always_migrate", "always_recompute".
    sim_bandwidth_mbps : float
        Fallback inter-node bandwidth estimate in MB/s, used when no gossiped
        measurement is available from LocalScheduler.
    monitor_interval_s : float
        Polling interval (seconds) for the built-in decode-worker health
        monitor in DecodingStageLLMEngine.
    monitor_enabled : bool
        Set to False to disable the built-in health monitor (useful in tests
        or when an external failure signal is wired in instead).
    log_file : str
        Path for the JSONL decision log written by ROMLogger.
    num_layers : int
        Number of transformer layers in the deployed model.
    num_kv_heads : int
        Number of key/value attention heads per layer.
    head_dim : int
        Dimensionality of each attention head (hidden_dim / num_heads).
    dtype_bytes : int
        Bytes per tensor element: 1 (int8), 2 (fp16/bf16), or 4 (fp32).
    prefill_time_table : dict[int, float]
        Pre-profiled prefill latencies: maps prompt-length buckets (tokens) to
        measured prefill time (seconds).  Generated by the profiling script
        under evaluation/0-test-single-forward-performance/.
        Keys should be in ascending order; values are interpolated linearly.
    """

    # ── Decision policy ──────────────────────────────────────────────────────
    policy: str = "rom"

    # ── Network / scheduler tuning ───────────────────────────────────────────
    # ~10 GB/s matches intra-node NVLink; drop to ~100 MB/s for inter-node IB.
    sim_bandwidth_mbps: float = 10_000.0

    # ── Built-in failure monitor ─────────────────────────────────────────────
    monitor_interval_s: float = 1.0
    monitor_enabled: bool = True

    # ── Logging ──────────────────────────────────────────────────────────────
    log_file: str = "/tmp/rom_decisions.jsonl"

    # ── Model architecture (required for KV-size computation) ────────────────
    # Default values match LLaMA-2-7B / OPT-6.7B.
    # Override via ROM_NUM_LAYERS, ROM_NUM_KV_HEADS, ROM_HEAD_DIM env vars
    # OR by calling LLMEngine.apply_model_config_to_rom(config) after init.
    num_layers: int = 32
    num_kv_heads: int = 32
    head_dim: int = 128
    dtype_bytes: int = 2  # fp16

    # ── Pre-profiled prefill time table ──────────────────────────────────────
    # Placeholder defaults scaled for a single A100 80GB with LLaMA-2-7B.
    # Replace with actual measurements from your hardware:
    #   python evaluation/0-test-single-forward-performance/profile_prefill.py
    prefill_time_table: Dict[int, float] = field(default_factory=lambda: {
        64:   0.005,
        128:  0.010,
        256:  0.018,
        512:  0.032,
        1024: 0.060,
        2048: 0.115,
        4096: 0.225,
        8192: 0.440,
    })

    # ─────────────────────────────────────────────────────────────────────────

    @classmethod
    def from_env(cls) -> "ROMConfig":
        """
        Build a ROMConfig from default values, then apply any ROM_* env-var
        overrides that are present.

        This is called once at LLMEngine startup so operators can tune the
        scheduler without changing source code.
        """
        cfg = cls()

        def _get(name: str):
            return os.environ.get(name)

        if v := _get("ROM_POLICY"):
            cfg.policy = v
        if v := _get("ROM_SIM_BANDWIDTH_MBPS"):
            cfg.sim_bandwidth_mbps = float(v)
        if v := _get("ROM_MONITOR_INTERVAL_S"):
            cfg.monitor_interval_s = float(v)
        if v := _get("ROM_MONITOR_ENABLED"):
            cfg.monitor_enabled = v.strip().lower() not in {"0", "false", "no"}
        if v := _get("ROM_LOG_FILE"):
            cfg.log_file = v
        if v := _get("ROM_NUM_LAYERS"):
            cfg.num_layers = int(v)
        if v := _get("ROM_NUM_KV_HEADS"):
            cfg.num_kv_heads = int(v)
        if v := _get("ROM_HEAD_DIM"):
            cfg.head_dim = int(v)
        if v := _get("ROM_DTYPE_BYTES"):
            cfg.dtype_bytes = int(v)

        cfg.validate()
        return cfg

    def validate(self) -> None:
        """
        Raise ValueError if any field has an invalid value.

        Called automatically by from_env(); call manually after programmatic
        construction.
        """
        if self.policy not in VALID_POLICIES:
            raise ValueError(
                f"ROM_POLICY must be one of {sorted(VALID_POLICIES)!r}, "
                f"got {self.policy!r}"
            )
        if self.sim_bandwidth_mbps <= 0:
            raise ValueError(
                f"sim_bandwidth_mbps must be > 0, got {self.sim_bandwidth_mbps}"
            )
        if self.monitor_interval_s <= 0:
            raise ValueError(
                f"monitor_interval_s must be > 0, got {self.monitor_interval_s}"
            )
        for attr in ("num_layers", "num_kv_heads", "head_dim"):
            v = getattr(self, attr)
            if v <= 0:
                raise ValueError(f"{attr} must be > 0, got {v}")
        if self.dtype_bytes not in (1, 2, 4):
            raise ValueError(
                f"dtype_bytes must be 1, 2, or 4, got {self.dtype_bytes}"
            )
        if not self.prefill_time_table:
            raise ValueError("prefill_time_table must not be empty")

    def update_from_model_config(
        self,
        num_layers: int,
        num_kv_heads: int,
        head_dim: int,
    ) -> None:
        """
        Overwrite architecture parameters with values read from the actual
        loaded model.  Called by LLMEngine after it initialises the workers
        and can query model metadata.

        Parameters
        ----------
        num_layers   : total transformer layers
        num_kv_heads : key/value head count per layer
        head_dim     : dimension of each head
        """
        self.num_layers = num_layers
        self.num_kv_heads = num_kv_heads
        self.head_dim = head_dim